# GitHub Labels Configuration
# Use with https://github.com/crazy-max/ghaction-github-labeler

## Type Labels
- name: 'bug'
  color: 'd73a4a'
  description: "Something isn't working"

- name: 'enhancement'
  color: 'a2eeef'
  description: 'New feature or request'

- name: 'documentation'
  color: '0075ca'
  description: 'Improvements or additions to documentation'

- name: 'design'
  color: 'f9d0c4'
  description: 'Design-related changes'

- name: 'refactoring'
  color: 'fbca04'
  description: 'Code refactoring'

- name: 'performance'
  color: 'ff7619'
  description: 'Performance improvements'

- name: 'testing'
  color: '0e8a16'
  description: 'Related to testing'

- name: 'maintenance'
  color: 'd4c5f9'
  description: 'Maintenance tasks and chores'

## Priority Labels
- name: 'priority: critical'
  color: 'b60205'
  description: 'Critical priority - security or production issues'

- name: 'priority: high'
  color: 'd93f0b'
  description: 'High priority'

- name: 'priority: medium'
  color: 'fbca04'
  description: 'Medium priority'

- name: 'priority: low'
  color: '0e8a16'
  description: 'Low priority'

## Status Labels
- name: 'status: blocked'
  color: 'd73a4a'
  description: 'Blocked by other issues or external factors'

- name: 'status: in progress'
  color: '0052cc'
  description: 'Work in progress'

- name: 'status: needs review'
  color: '0e8a16'
  description: 'Ready for review'

- name: 'status: on hold'
  color: 'fbca04'
  description: 'On hold'

## Special Labels
- name: 'good first issue'
  color: '7057ff'
  description: 'Good for newcomers'

- name: 'help wanted'
  color: '008672'
  description: 'Extra attention is needed'

- name: 'question'
  color: 'd876e3'
  description: 'Further information is requested'

- name: 'duplicate'
  color: 'cfd3d7'
  description: 'This issue or pull request already exists'

- name: 'invalid'
  color: 'e4e669'
  description: "This doesn't seem right"

- name: 'wontfix'
  color: 'ffffff'
  description: 'This will not be worked on'

- name: 'stale'
  color: 'fef2c0'
  description: 'No recent activity'

- name: 'security'
  color: 'ee0701'
  description: 'Security-related issues'

- name: 'dependencies'
  color: '0366d6'
  description: 'Dependency updates'

- name: 'pinned'
  color: 'fbca04'
  description: "Pinned - won't be marked as stale"

- name: 'work-in-progress'
  color: 'f9d0c4'
  description: 'Work in progress - not ready for review'
